/*
 * Copyright 2025-2026 Integrallis Software, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.integrallis.vectors.vcr;

import static org.assertj.core.api.Assertions.assertThat;

import com.integrallis.vectors.storage.backend.HeapStorageBackend;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Pins the parallel-execution contract for {@link VCRContext}. Both JUnit5 and TestNG framework
 * adapters share one {@code VCRContext} per test class and call {@code setCurrentTest} + {@code
 * generateCassetteKey} on it from whichever thread the framework picks. Under
 * {@code @Execution(CONCURRENT)} (JUnit5) or {@code parallel="methods"} (TestNG), that thread is
 * not the same one between consecutive calls — so the per-thread test id and cassette-key sequence
 * must not be sharable global state. Without per-thread isolation, a key generated by thread T1 can
 * come back stamped with T2's test id (= wrong cassette read/written).
 */
@Tag("unit")
class VCRContextConcurrencyTest {

  private VCRContext newContext() {
    HeapStorageBackend backend = new HeapStorageBackend();
    ExactCassetteStore store = new ExactCassetteStore(backend, new TestSerializer());
    VCRRegistry registry = new VCRRegistry(backend);
    return new VCRContext(store, registry, VCRMode.RECORD);
  }

  @Test
  void generateCassetteKey_returnsCallersTestId_underParallelMethods() throws Exception {
    VCRContext ctx = newContext();
    int threads = 16;
    int callsPerThread = 200;
    CountDownLatch start = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(threads);
    List<String> mismatches = Collections.synchronizedList(new ArrayList<>());

    try (var pool = Executors.newFixedThreadPool(threads)) {
      for (int t = 0; t < threads; t++) {
        String myTestId = "Suite:test-" + t;
        pool.submit(
            () -> {
              try {
                start.await();
                // Simulates what the framework adapter does in beforeTestExecution / @BeforeMethod
                // for this thread's method invocation.
                ctx.resetCallCounters();
                ctx.setCurrentTest(myTestId);
                for (int i = 0; i < callsPerThread; i++) {
                  CassetteKey k = ctx.generateCassetteKey("embedding");
                  if (!myTestId.equals(k.testId())) {
                    mismatches.add(
                        "thread for "
                            + myTestId
                            + " got key with testId="
                            + k.testId()
                            + " callIndex="
                            + k.callIndex());
                    return;
                  }
                }
              } catch (Exception e) {
                mismatches.add("thread " + myTestId + " threw: " + e);
              } finally {
                done.countDown();
              }
            });
      }
      start.countDown();
      assertThat(done.await(15, TimeUnit.SECONDS))
          .as("all threads must complete within budget")
          .isTrue();
    }

    assertThat(mismatches)
        .as(
            "every cassette key must carry the testId of the thread that asked for it — "
                + "without per-thread isolation, a key requested by T1 can return stamped with T2's id, "
                + "which means we read/write the wrong cassette under @Execution(CONCURRENT).")
        .isEmpty();
  }

  @Test
  void callCountersAreIsolatedPerTestId_underParallelMethods() throws Exception {
    VCRContext ctx = newContext();
    int threads = 8;
    int callsPerThread = 50;
    CountDownLatch start = new CountDownLatch(1);
    CountDownLatch done = new CountDownLatch(threads);
    List<String> failures = Collections.synchronizedList(new ArrayList<>());

    try (var pool = Executors.newFixedThreadPool(threads)) {
      for (int t = 0; t < threads; t++) {
        String myTestId = "Suite:test-" + t;
        pool.submit(
            () -> {
              try {
                start.await();
                ctx.resetCallCounters();
                ctx.setCurrentTest(myTestId);
                int previous = 0;
                for (int i = 0; i < callsPerThread; i++) {
                  CassetteKey k = ctx.generateCassetteKey("embedding");
                  if (!myTestId.equals(k.testId())) {
                    failures.add("wrong testId on key: " + k);
                    return;
                  }
                  // Within a single thread/test, callIndex must increment monotonically by 1.
                  if (k.callIndex() != previous + 1) {
                    failures.add(
                        "expected callIndex "
                            + (previous + 1)
                            + " for "
                            + myTestId
                            + " but got "
                            + k.callIndex()
                            + " — counter was clobbered by a peer thread's resetCallCounters().");
                    return;
                  }
                  previous = k.callIndex();
                }
              } catch (Exception e) {
                failures.add("thread " + myTestId + " threw: " + e);
              } finally {
                done.countDown();
              }
            });
      }
      start.countDown();
      assertThat(done.await(15, TimeUnit.SECONDS)).isTrue();
    }

    assertThat(failures)
        .as("counter sequences must be isolated per (thread, testId, type)")
        .isEmpty();
  }
}
