/*
 * Copyright 2025-2026 Integrallis Software, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.integrallis.vectors.studio.sidecart.sources;

import com.integrallis.vectors.studio.sidecart.SidecartRecord;
import com.integrallis.vectors.studio.sidecart.SidecartSource;
import com.integrallis.vectors.studio.sidecart.SidecartSourceException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import java.util.Optional;

/**
 * Sidecart source backed by a flat directory tree. The on-disk file for a document {@code id} is
 * resolved as {@code baseDir / sanitize(id) + extension}. {@code id} is sanitised (path separators
 * are rewritten to {@code _}) so that ids generated by chunkers — which often embed colons,
 * slashes, and dots — cannot escape the base directory.
 *
 * <p>If {@code textMode} is {@code true} the file content is decoded as UTF-8 text; otherwise the
 * raw bytes are returned as a blob with {@code mimeType}.
 */
public final class FileSidecartSource implements SidecartSource {

  private final Path baseDir;
  private final String extension;
  private final boolean textMode;
  private final String mimeType;

  /**
   * @param baseDir directory that holds the sidecart files
   * @param extension file extension (with leading dot, e.g. {@code ".png"}); empty disables
   * @param textMode true → decode bytes as UTF-8 text; false → return raw bytes
   * @param mimeType MIME type to attach to blob responses (ignored when {@code textMode})
   */
  public FileSidecartSource(Path baseDir, String extension, boolean textMode, String mimeType) {
    this.baseDir = Objects.requireNonNull(baseDir, "baseDir").toAbsolutePath().normalize();
    this.extension = extension == null ? "" : extension;
    this.textMode = textMode;
    this.mimeType = mimeType;
  }

  @Override
  public Optional<SidecartRecord> get(String id) {
    if (id == null || id.isEmpty()) return Optional.empty();
    Path candidate = baseDir.resolve(sanitise(id) + extension).normalize();
    if (!candidate.startsWith(baseDir)) {
      throw new SidecartSourceException("id resolves outside baseDir: " + id);
    }
    if (!Files.isRegularFile(candidate)) return Optional.empty();
    try {
      byte[] bytes = Files.readAllBytes(candidate);
      if (textMode) {
        return Optional.of(
            SidecartRecord.ofText(new String(bytes, StandardCharsets.UTF_8), mimeType));
      }
      return Optional.of(SidecartRecord.ofBlob(bytes, mimeType));
    } catch (IOException e) {
      throw new SidecartSourceException("failed to read " + candidate, e);
    }
  }

  static String sanitise(String id) {
    StringBuilder sb = new StringBuilder(id.length());
    for (int i = 0; i < id.length(); i++) {
      char c = id.charAt(i);
      if (c == '/' || c == '\\' || c == ':' || c == '\0') {
        sb.append('_');
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }
}
